export * from './Auth';
export * from './Home';
export * from './Auth';
export * from './NowShowing';
export * from './Customer';
export * from './AllCGV';
export * from './Booking';
export * from './Checkout';
export { default as CommingSoonTemplate } from './CommingSoonTemplate';
export { default as MovieDetailTemplate } from './MovieDetailTemplate';
export { default as UpdatingPageTemplate } from './UpdatingPageTemplate';
