export * from './AuthTemplate';
export * from './HomeTemplate';
export * from './AuthTemplate';
export * from './NowShowingTemplate';
export * from './CommingSoonTemplate';
export * from './MovieDetailTemplate';
export * from './UpdatingPageTemplate';
export * from './AccountTemplate';
export * from './AccountDetailTemplate';